### ISSUE TITLE
Implement Horizon Cache

### ISSUE THREAD

**Issue by bshephar** [openstack-k8s-operators/horizon-operator#28]
Horizon uses memcached to cache credentials and fails without a cache configured:

```
[Wed Feb 15 02:39:39.404211 2023] [authz_core:debug] [pid 182:tid 186] mod_authz_core.c(843): [client 10.130.0.2:57378] AH01628: authorization result: granted (no directives), referer: http://horizon-public-openstack.apps.okd.bne-shift.net/dashboard/auth/login/?next=/dashboard/
[Wed Feb 15 02:39:39.434300 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378] DEBUG openstack_auth.backend Beginning user authentication
[Wed Feb 15 02:39:39.434961 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378] DEBUG openstack_auth.plugin.password Attempting to authenticate for admin
[Wed Feb 15 02:39:39.435914 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378] DEBUG keystoneauth.identity.v3.base Making authentication request to http://keystone-public-openstack.apps.okd.bne-shift.net/v3/auth/tokens
[Wed Feb 15 02:39:39.702850 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378] DEBUG keystoneauth.session Request returned failure status: 503
[Wed Feb 15 02:39:39.703169 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378] DEBUG openstack_auth.plugin.base Service Unavailable (HTTP 503)
[Wed Feb 15 02:39:39.703386 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378] INFO openstack_auth.forms Login failed for user "admin" using domain "Default", remote address 10.130.0.2.
[Wed Feb 15 02:39:42.968282 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378] ERROR django.request Internal Server Error: /dashboard/auth/login/
[Wed Feb 15 02:39:42.968332 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378] Traceback (most recent call last):
[Wed Feb 15 02:39:42.968337 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]   File "/usr/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
[Wed Feb 15 02:39:42.968341 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]     response = get_response(request)
[Wed Feb 15 02:39:42.968344 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]   File "/usr/lib/python3.9/site-packages/django/utils/deprecation.py", line 119, in __call__
[Wed Feb 15 02:39:42.968348 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]     response = self.process_response(request, response)
[Wed Feb 15 02:39:42.968351 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]   File "/usr/lib/python3.9/site-packages/django/contrib/sessions/middleware.py", line 61, in process_response
[Wed Feb 15 02:39:42.968354 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]     request.session.save()
[Wed Feb 15 02:39:42.968357 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]   File "/usr/lib/python3.9/site-packages/django/contrib/sessions/backends/cache.py", line 56, in save
[Wed Feb 15 02:39:42.968361 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]     return self.create()
[Wed Feb 15 02:39:42.968364 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]   File "/usr/lib/python3.9/site-packages/django/contrib/sessions/backends/cache.py", line 50, in create
[Wed Feb 15 02:39:42.968367 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378]     raise RuntimeError(
[Wed Feb 15 02:39:42.968370 2023] [wsgi:error] [pid 66:tid 124] [remote 10.130.0.2:57378] RuntimeError: Unable to create a new session key. It is likely that the cache is unavailable.
```

We need to configure the cache section of local_settings once the memcached operator is available:
https://github.com/openstack-k8s-operators/horizon-operator/blob/main/templates/horizon/config/local_settings.py#L131-L141

**Comment by deshipu** [comment]
Can we close this? It seems to be implemented in 
https://github.com/openstack-k8s-operators/horizon-operator/blob/main/templates/horizon/config/local_settings.py#L108-L115

Do we need to add some configuration for memcached when tls is enabled? Certificates?
